FROM node:22-alpine
WORKDIR /.
COPY package* .
COPY ./packages/prisma
# Declare build-time arguments
ARG DATABASE_URL
ARG NEXTAUTH_SECRET

# Expose the arguments as environment variables inside the container
ENV DATABASE_URL=$DATABASE_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
RUN npm i
RUN cd packages && npx prisma generate && cd ..
COPY ..
RUN npm run build
EXPOSE 3000
CMD ["npm","start"]
